window.BACKEND_URL = "http://localhost:8080";
window.USER_ENDPOINT = window.BACKEND_URL + "/user";
window.PRODUCT_ENDPOINT = window.BACKEND_URL + "/product";
window.CATEGORY_ENDPOINT = window.BACKEND_URL + "/category";
window.AUTHOR_ENDPOINT = window.BACKEND_URL + "/author";
window.IMAGE_ENDPOINT = window.BACKEND_URL + "/image";
window.LOGOUT_ENDPOINT = window.BACKEND_URL + "/auth/logout";
window.LOGIN_ENDPOINT = window.BACKEND_URL + "/auth/login"
window.BASKETITEM_ENDPOINT = window.BACKEND_URL + "/basketItem"