name: Build and Deploy

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image for frontend
      run: docker build -t vulpeszerda27/bookshop-frontend:latest .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image for frontend
      run: docker push vulpeszerda27/bookshop-frontend:latest

    # Set up SSH for deployment
    - name: Setup SSH
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key

    # Execute script on remote server to deploy using docker-compose
    - name: Deploy to remote server
      run: ssh -o StrictHostKeyChecking=no -i private_key root@${{ secrets.SERVER_IP }} './deploy_webshop.sh'

